stages:
  - build
  - test
  - publish
  - deploy

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet restore ecmis-witness.sln
    - dotnet build ecmis-witness.sln --no-restore -c Release
  only:
    - develop
    - main
    - /^feature\/.*/
    - /^release\/.*/

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet test tests/EcmisWitness.Tests/EcmisWitness.Tests.csproj --no-build -c Release
  only:
    - develop
    - main
    - /^feature\/.*/

docker:build:
  stage: publish
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - develop
    - main
    - /^release\/.*/

deploy:dev:
  stage: deploy
  script:
    - echo "Deploy ecmis-witness to Dev"
  environment:
    name: development
  only:
    - develop

deploy:staging:
  stage: deploy
  script:
    - echo "Deploy ecmis-witness to Staging"
  environment:
    name: staging
  only:
    - /^release\/.*/

deploy:production:
  stage: deploy
  script:
    - echo "Deploy ecmis-witness to Production"
  environment:
    name: production
  when: manual
  only:
    - main
